---
service_name: "etcd"
etcd_server_version: "3.5.16-10"
etcd_client_version: "3.5.16-10"
initial_cluster_token: "etcd-cluster"
initial_cluster: "etcd-1=https://192.168.1.61:2380,etcd-2=https://192.168.1.62:2380,etcd-3=https://192.168.1.63:2380"
