- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install haproxy
  ansible.builtin.apt:
    pkg:
      - "haproxy={{ haproxy_version }}"
  notify: Reload systemd and restart haproxy service

- name: Install keppalived
  ansible.builtin.apt:
    pkg:
      - "psmisc={{ psmisc_version }}"
      - "keepalived={{ keepalived_version }}"
  notify: Reload systemd and restart keepalived service

- name: Create a sysctl config file
  ansible.builtin.file:
    path: "/etc/sysctl.d/{{ item }}"
    state: touch
    mode: "0644"
    owner: root
    group: root
  loop:
    - 99-ip-forward.conf
    - 98-ip-nonlocal-bind.conf

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: true
    reload: true
    sysctl_file: /etc/sysctl.d/99-ip-forward.conf

- name: Enable IPv4 nonlocal binding
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/98-ip-nonlocal-bind.conf

- name: Deploy complete haproxy configuration file
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd and restart haproxy service

- name: Deploy complete keepalived configuration file
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd and restart keepalived service

- name: Deploy haproxy status check configuration file for keeaplived
  ansible.builtin.template:
    src: files/check_haproxy.sh
    dest: /etc/keepalived/check_haproxy.sh
    owner: root
    group: root
    mode: "0755"

- name: Create systemd drop-in directory for keepalived
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ keepalived_service_name }}.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create drop-in configuration file for keepalived
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ keepalived_service_name }}.service.d/10-custom-overrides.conf"
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5
      [Unit]
      After=network-online.target
      Wants=network-online.target haproxy.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd and restart keepalived service
