- name: Include a play for base
  ansible.builtin.import_playbook: base.yml

- name: Include a play for database
  ansible.builtin.import_playbook: db.yml

- name: Include a play for web
  ansible.builtin.import_playbook: web.yml
