- name: Set timezone to Asia/Kolkata
  become: true
  community.general.timezone:
    name: Asia/Kolkata

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install basic packages
  ansible.builtin.apt:
    pkg:
      - "vim={{ common_vim_version }}"
      - "net-tools={{ common_net_tools_version }}"
      - "tmux={{ common_tmux_version }}"
