- name: Create directory for ca cert
  ansible.builtin.file:
    path: /etc/kubernetes/pki/etcd/
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy CA Certificate
  ansible.builtin.copy:
    src: files/certs/ca.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt
    owner: root
    group: root
    mode: "0644"

- name: Copy required Certificates and keys
  ansible.builtin.copy:
    src: files/certs/{{ item }}
    dest: /etc/kubernetes/pki/
    owner: root
    group: root
    mode: "0644"
  loop:
    - "{{ inventory_hostname }}.crt"
    - "{{ inventory_hostname }}-private.key"
  when: inventory_hostname == "k8s-master-1"

- name: Copy k8s init configuration file
  ansible.builtin.template:
    src: master_config.j2
    dest: /root/master_config.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == "k8s-master-1"
